name: My First Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello from GitHub Actions!"

      - name: Show current date
        run: date

      - name: Show folder structure
        run: ls -la

  check-system:
    runs-on: ubuntu-latest
    needs: say-hello
    steps:
      - name: Check OS
        run: uname -a

      - name: Check available memory
        run: free -h
   
   failing-job:
    runs-on: ubuntu-latest
    needs: check-system
    steps:
      - name: This will fail
        run: exit 1

      - name: This will never run
        run: echo "I am unreachable"

