name: My First Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: echo "My secret is ${{ secrets.MY_SECRET_MESSAGE }}"
