name: My First Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21]
    steps:
      - name: Test on Java ${{ matrix.java }}
        run: echo "Running tests on Java version ${{ matrix.java }}"
